"""
Build held-out test sets for Phase 0 baseline.

`tests/synthetic/`: 50 HR images sampled deterministically from datasets/HR_train,
paired with LQ images generated by DegradationMachine (so we have GT for PSNR/SSIM/LPIPS).

`tests/historical/`: directory placeholder — user must populate with real scanned
historical photos (no GT). We only create the directory and a README pointing at sources.

Usage:
    python scripts/build_test_sets.py
    python scripts/build_test_sets.py --n 50 --seed 42 --regenerate
"""

import argparse
import json
import random
import shutil
import sys
from pathlib import Path

import cv2
import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "BasicSR"))

from basicsr.degradation_machine import DegradationMachine  # noqa: E402


def collect_hr_images(hr_dir: Path) -> list[Path]:
    exts = {".png", ".jpg", ".jpeg", ".webp", ".bmp"}
    return sorted(p for p in hr_dir.iterdir() if p.suffix.lower() in exts)


def build_synthetic(
    hr_dir: Path,
    out_dir: Path,
    n: int,
    seed: int,
    regenerate: bool,
):
    gt_out = out_dir / "GT"
    lq_out = out_dir / "LQ"
    gt_out.mkdir(parents=True, exist_ok=True)
    lq_out.mkdir(parents=True, exist_ok=True)

    sample_record = out_dir / "sample_paths.json"
    if sample_record.exists() and not regenerate:
        with sample_record.open() as f:
            chosen_names = json.load(f)["chosen"]
        chosen = [hr_dir / name for name in chosen_names]
        print(f"[reuse] {len(chosen)} images from {sample_record}")
    else:
        all_paths = collect_hr_images(hr_dir)
        if len(all_paths) < n:
            raise RuntimeError(f"HR_train has only {len(all_paths)} images, need {n}")
        rng = random.Random(seed)
        chosen = rng.sample(all_paths, n)
        with sample_record.open("w") as f:
            json.dump(
                {"seed": seed, "n": n, "chosen": [p.name for p in chosen]},
                f,
                indent=2,
            )
        print(f"[sampled] {len(chosen)} images written to {sample_record}")

    # Seed numpy/random globally so DegradationMachine is reproducible
    random.seed(seed)
    np.random.seed(seed)
    degrader = DegradationMachine()

    written = 0
    for idx, hr_path in enumerate(chosen):
        gt_dst = gt_out / hr_path.name
        lq_dst = lq_out / hr_path.name

        if gt_dst.exists() and lq_dst.exists() and not regenerate:
            written += 1
            continue

        img = cv2.imread(str(hr_path), cv2.IMREAD_COLOR)
        if img is None:
            print(f"[skip] cannot read {hr_path}")
            continue

        h, w = img.shape[:2]
        # Crop to multiple of 4 so 4x SR aligns with GT
        h4, w4 = h - (h % 4), w - (w % 4)
        img = img[:h4, :w4]

        # Re-seed per-image so each image's degradation is reproducible
        per_img_seed = seed + idx
        random.seed(per_img_seed)
        np.random.seed(per_img_seed)

        lq = degrader.run(img)

        cv2.imwrite(str(gt_dst), img)
        cv2.imwrite(str(lq_dst), lq)
        written += 1

    print(f"[synthetic] wrote {written}/{len(chosen)} pairs to {out_dir}")


def scaffold_historical(out_dir: Path):
    out_dir.mkdir(parents=True, exist_ok=True)
    readme = out_dir / "README.md"
    if not readme.exists():
        readme.write_text(
            "# Historical test set (no GT)\n\n"
            "Drop 30-50 real scanned historical photographs here. "
            "Use only public-domain sources and record provenance.\n\n"
            "Suggested sources:\n"
            "- Library of Congress (LoC) — pre-1929 US public domain\n"
            "- Europeana CC0 collection\n"
            "- Croatian State Archives (HDA), Digitalna zbirka\n"
            "- Wikimedia Commons (filter for {{PD-old}})\n\n"
            "Document one line per image in `provenance.csv`:\n"
            "    filename, source_url, year, license\n",
            encoding="utf-8",
        )
    prov = out_dir / "provenance.csv"
    if not prov.exists():
        prov.write_text("filename,source_url,year,license\n", encoding="utf-8")
    print(f"[historical] scaffolded {out_dir} (populate manually)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--hr-dir", default=str(REPO_ROOT / "datasets" / "HR_train"))
    ap.add_argument("--out-root", default=str(REPO_ROOT / "tests"))
    ap.add_argument("--n", type=int, default=50)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--regenerate", action="store_true")
    args = ap.parse_args()

    hr_dir = Path(args.hr_dir)
    out_root = Path(args.out_root)

    build_synthetic(hr_dir, out_root / "synthetic", args.n, args.seed, args.regenerate)
    scaffold_historical(out_root / "historical")


if __name__ == "__main__":
    main()
